# Generated by Django 6.1.1 on 2026-10-05 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradingsignal',
            old_name='MomentumScore',
            new_name='momentum_score',
        ),
    ]
